import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const gameStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0e27',
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#1a1f3a',
    borderBottomWidth: 2,
    borderBottomColor: '#2a3f5f',
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#00d4ff',
    textAlign: 'center',
    textShadowColor: '#00d4ff',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  statBox: {
    alignItems: 'center',
    backgroundColor: '#0f1629',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2a3f5f',
  },
  statLabel: {
    fontSize: 12,
    color: '#7a8aa3',
    marginBottom: 2,
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#00ff88',
  },
  gameBoard: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  grid: {
    backgroundColor: '#1a1f3a',
    borderRadius: 15,
    padding: 10,
    shadowColor: '#00d4ff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
  },
  row: {
    flexDirection: 'row',
  },
  cell: {
    width: width / 5,
    height: width / 5,
    margin: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 2,
    position: 'relative',
  },
  cellUnvisited: {
    backgroundColor: '#0f1629',
    borderColor: '#2a3f5f',
  },
  cellVisited: {
    backgroundColor: '#1a2540',
    borderColor: '#3a4f7f',
  },
  cellCurrent: {
    backgroundColor: '#2a4a6a',
    borderColor: '#00d4ff',
    shadowColor: '#00d4ff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 8,
    elevation: 8,
  },
  cellDanger: {
    backgroundColor: '#3a1a1a',
    borderColor: '#ff4444',
  },
  cellContent: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cellIcon: {
    fontSize: 32,
  },
  player: {
    fontSize: 36,
  },
  perceptsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: '#1a1f3a',
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: '#2a3f5f',
  },
  perceptBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0f1629',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    margin: 5,
    borderWidth: 1,
  },
  perceptActive: {
    borderColor: '#ff6b6b',
    backgroundColor: '#2a1a1a',
  },
  perceptInactive: {
    borderColor: '#2a3f5f',
    opacity: 0.5,
  },
  perceptIcon: {
    fontSize: 16,
    marginRight: 5,
  },
  perceptText: {
    fontSize: 14,
    color: '#ffffff',
    fontWeight: '600',
  },
  controlsContainer: {
    padding: 20,
    backgroundColor: '#1a1f3a',
  },
  controlsTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#00d4ff',
    marginBottom: 15,
    textAlign: 'center',
  },
  controlsGrid: {
    alignItems: 'center',
  },
  directionControls: {
    alignItems: 'center',
    marginBottom: 15,
  },
  controlRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 5,
  },
  actionControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
  },
  controlButton: {
    backgroundColor: '#2a4a6a',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    margin: 5,
    minWidth: 80,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#3a5f8f',
    shadowColor: '#00d4ff',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  controlButtonDisabled: {
    backgroundColor: '#1a2540',
    borderColor: '#2a3f5f',
    opacity: 0.5,
  },
  controlButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  newGameButton: {
    backgroundColor: '#00d4ff',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    margin: 10,
    alignItems: 'center',
    shadowColor: '#00d4ff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 8,
  },
  newGameButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#0a0e27',
  },
  messageContainer: {
    backgroundColor: '#1a1f3a',
    padding: 15,
    marginHorizontal: 20,
    marginTop: 10,
    borderRadius: 10,
    borderLeftWidth: 4,
  },
  messageInfo: {
    borderLeftColor: '#00d4ff',
  },
  messageSuccess: {
    borderLeftColor: '#00ff88',
  },
  messageDanger: {
    borderLeftColor: '#ff4444',
  },
  messageText: {
    fontSize: 16,
    color: '#ffffff',
    fontWeight: '600',
  },
  gameOverOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(10, 14, 39, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  gameOverContent: {
    backgroundColor: '#1a1f3a',
    padding: 40,
    borderRadius: 20,
    alignItems: 'center',
    borderWidth: 3,
    minWidth: width * 0.8,
  },
  gameOverWin: {
    borderColor: '#00ff88',
  },
  gameOverLose: {
    borderColor: '#ff4444',
  },
  gameOverTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  gameOverTitleWin: {
    color: '#00ff88',
  },
  gameOverTitleLose: {
    color: '#ff4444',
  },
  gameOverStats: {
    width: '100%',
    marginVertical: 20,
  },
  gameOverStatRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#2a3f5f',
  },
  gameOverStatLabel: {
    fontSize: 18,
    color: '#7a8aa3',
  },
  gameOverStatValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#00d4ff',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0a0e27',
  },
  loadingText: {
    fontSize: 20,
    color: '#00d4ff',
    marginTop: 20,
  },
});